'use client';
import { Fragment, useEffect, useState, type FormEvent, type ReactNode } from 'react';
import type { AdminKey } from '@field-service/i18n';
import { call, dateTime, isSuperAdmin, money, useLanguage, useStepUp, useText, type Me } from './api';

export const localTime=(value=new Date().toISOString())=>new Date(new Date(value).getTime()+7*3600000).toISOString().slice(0,16);
export const instant=(value:string)=>new Date(`${value}:00+07:00`).toISOString();
function errorText(e:unknown){return e instanceof Error?e.message:String(e);}
export function Feedback({error,done}:{error:string;done?:string}){return <>{error?<p className="error" role="alert">{error}</p>:null}{done?<p className="ok-box" role="status">{done}</p>:null}</>;}
export function Editor({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const t=useText();return <section className="panel"><div className="actions"><h2>{title}</h2><button type="button" className="ghost" onClick={onClose}>{t('cancel')}</button></div>{children}</section>;}
export function useWork(){const t=useText(),[error,setError]=useState(''),[done,setDone]=useState(''),[busy,setBusy]=useState(false);return {error,done,busy,setError,run:async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');setDone('');try{await fn();setDone(t('saved'));}catch(e){setError(errorText(e)||t('settingsError'));}finally{setBusy(false);}}};}
type Staff={id:string;version:number;display_name:string;email:string;status:string;mfa_enrolled:boolean;active_sessions:number;roles:string[]};
type StaffData={items:Staff[];has_more:boolean;roles:{code:string;permissions:string[]}[]};
export function StaffView({me}:{me:Me}){
 const t=useText(),step=useStepUp(),w=useWork();const [data,setData]=useState<StaffData|null>(null),[q,setQ]=useState(''),[query,setQuery]=useState(''),[offset,setOffset]=useState(0);
 const [editor,setEditor]=useState<Staff|'invite'|null>(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[roles,setRoles]=useState<string[]>([]),[why,setWhy]=useState(''),[link,setLink]=useState('');
 async function load(){const d=await call<StaffData>('GET',`/platform/staff?q=${encodeURIComponent(query)}&offset=${offset}`);setData(d);}
 useEffect(()=>{void load().catch(e=>w.setError(errorText(e)));},[query,offset]);
 function edit(row:Staff|'invite'){setEditor(row);setRoles(row==='invite'?['support_agent']:row.roles);setWhy('');setName('');setEmail('');setLink('');}
 async function save(e:FormEvent){e.preventDefault();await w.run(async()=>{if(editor==='invite'){const d=await step(()=>call<{token:string}>('POST','/platform/staff/invite',{display_name:name,email,roles}));setLink(`${location.origin}/console#invite=${encodeURIComponent(d.token)}`);}
 else if(editor)await step(()=>call('POST','/platform/changes',{kind:'roles',target_id:editor.id,version:editor.version,payload:{roles},reason:why}));setEditor(null);await load();});}
 async function action(row:Staff,value:string){const reason=prompt(t('confirmationReason'));if(!reason?.trim())return;await w.run(async()=>{await step(()=>call('POST',`/platform/staff/${row.id}/action`,{action:value,version:row.version,reason}));await load();});}
 async function recover(row:Staff,reinvite:boolean){const reason=prompt(`${t('recoveryHint')}\n${t('confirmationReason')}`);if(!reason?.trim())return;await w.run(async()=>{if(reinvite){const d=await step(()=>call<{token:string}>('POST',`/platform/staff/${row.id}/reinvite`,{version:row.version,reason}));setLink(`${location.origin}/console#invite=${encodeURIComponent(d.token)}`);}else await step(()=>call('POST','/platform/changes',{kind:'recovery',target_id:row.id,version:row.version,reason}));await load();});}
 return <><h1>{t('navStaff')}</h1><p className="muted">{t('staffHint')}</p><Feedback {...w}/><div className="actions"><button className="primary" disabled={w.busy} onClick={()=>edit('invite')}>{t('inviteStaff')}</button><button className="ghost" disabled={w.busy} onClick={()=>w.run(load)}>{t('reloadSettings')}</button></div>
 {link?<section className="panel"><label>{t('inviteLink')}<input readOnly value={link}/></label><p>{t('inviteLinkHint')}</p><button type="button" onClick={()=>setLink('')}>{t('cancel')}</button></section>:null}
 {editor?<Editor title={t(editor==='invite'?'inviteStaff':'editRoles')} onClose={()=>setEditor(null)}><form onSubmit={save}>{editor==='invite'?<div className="grid2"><label>{t('profileName')}<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t('email')}<input required type="email" maxLength={200} value={email} onChange={e=>setEmail(e.target.value)}/></label></div>:<p>{editor.display_name} · {editor.email}<br/>{t(isSuperAdmin(me)?'superAdminDirectHint':'roleApprovalHint')}</p>}
 <fieldset><legend>{t('roles')}</legend>{data?.roles.filter(r=>editor!=='invite'||!['super_admin','billing_approver'].includes(r.code)).map(r=><label className="check" key={r.code}><input type="checkbox" checked={roles.includes(r.code)} onChange={e=>setRoles(e.target.checked?[...roles,r.code]:roles.filter(x=>x!==r.code))}/><span>{r.code}<small className="muted permissions-list">{r.permissions.join(' · ')}</small></span></label>)}</fieldset>
 {editor!=='invite'?<label>{t('reason')}<textarea required maxLength={500} value={why} onChange={e=>setWhy(e.target.value)}/></label>:null}<button className="primary" disabled={w.busy||!roles.length}>{t(editor==='invite'?'inviteStaff':isSuperAdmin(me)?'applyNow':'requestApproval')}</button></form></Editor>:null}
 <form className="inline" onSubmit={e=>{e.preventDefault();setOffset(0);setQuery(q);}}><label className="grow">{t('searchStaff')}<input value={q} onChange={e=>setQ(e.target.value)}/></label><button>{t('confirm')}</button></form>
 <div className="table-scroll"><table><thead><tr><th>{t('profileName')}</th><th>{t('roles')}</th><th>{t('status')}</th><th>{t('staffSessions')}</th><th/></tr></thead><tbody>{data?.items.map(r=><tr key={r.id}><td>{r.display_name}<div className="muted">{r.email}</div></td><td>{r.roles.join(', ')}</td><td>{t(r.status==='active'?'staffActive':r.status==='invited'?'staffInvited':'staffDisabled')}<div className="muted">{r.mfa_enrolled?t('mfaEnabled'):'—'}</div></td><td>{r.active_sessions}</td><td>{r.id!==me.id?<div className="actions">{r.status==='invited'?<button disabled={w.busy} onClick={()=>recover(r,true)}>{t('reinviteStaff')}</button>:r.status==='active'?<button disabled={w.busy} onClick={()=>recover(r,false)}>{t('staffRecovery')}</button>:null}<button disabled={w.busy||r.status==='disabled'} onClick={()=>edit(r)}>{t('editRoles')}</button>{r.status==='disabled'&&r.mfa_enrolled?<button disabled={w.busy} onClick={()=>action(r,'enable')}>{t('enableStaff')}</button>:r.status!=='disabled'?<button className="danger" disabled={w.busy} onClick={()=>action(r,'disable')}>{t('disableStaff')}</button>:null}<button disabled={w.busy||!r.active_sessions} onClick={()=>action(r,'revoke_sessions')}>{t('revokeStaff')}</button></div>:null}</td></tr>)}</tbody></table></div>{data&&!data.items.length?<p>{t('empty')}</p>:null}<div className="actions"><button disabled={!offset||w.busy} onClick={()=>setOffset(Math.max(0,offset-50))}>{t('backPage')}</button><span>{offset+1}</span><button disabled={!data?.has_more||w.busy} onClick={()=>setOffset(offset+50)}>{t('nextPage')}</button></div></>;
}
type Change={id:string;kind:'roles'|'recovery'|'plan'|'policy';target_id:string|null;payload:Record<string,unknown>;status:string;reason:string;requested_by:string;requester:string;created_at:string;decision_note:string|null;target:{display_name:string;email:string;status:string;roles:string[]}|null};
/** What an approver is deciding, in words instead of the raw request body. */
function ChangeDetails({row}:{row:Change}){
 const t=useText(),lang=useLanguage(),p=row.payload;
 const target=row.target?<p>{t('changeTarget')}: <strong>{row.target.display_name}</strong> · {row.target.email} <span className="muted">({row.target.roles.join(', ')||'—'})</span></p>:null;
 if(row.kind==='roles')return <>{target}<p>{t('newRoles')}: <strong>{(p.roles as string[]|undefined)?.join(', ')}</strong></p></>;
 if(row.kind==='recovery')return <>{target}<p className="caution">{t('recoverySummary')}</p></>;
 if(row.kind==='plan'){const d=p as unknown as DraftPayload;return <dl className="facts">
  <dt>{t('planCode')}</dt><dd>{d.code} · {lang==='th'?d.name_th:d.name_en} ({t(d.kind==='trial'?'trialPlan':'paidPlan')})</dd>
  <dt>{t('seats')}</dt><dd>{d.technician_seats}</dd><dt>{t('storageGb')}</dt><dd>{Number(d.storage_bytes)/1e9}</dd>
  <dt>{t('trialDays')}</dt><dd>{d.trial_days}</dd><dt>{t('graceDays')}</dt><dd>{d.grace_days}</dd>
  {d.prices?.map(pr=><Fragment key={pr.interval_unit}><dt>{t(pr.interval_unit==='year'?'yearlyPrice':'monthlyPrice')}</dt><dd>{money(pr.amount_minor,lang)}</dd></Fragment>)}
  <dt>{t('effectiveAt')}</dt><dd>{dateTime(d.effective_at,lang)}</dd></dl>;}
 const days=(v:unknown)=>v===null||v===undefined?'—':String(v);
 return <dl className="facts"><dt>{t('allowNewShops')}</dt><dd>{t(p.new_shops_enabled?'yes':'no')}</dd><dt>{t('allowNewPayments')}</dt><dd>{t(p.new_payments_enabled?'yes':'no')}</dd>
  <dt>{t('businessRetentionDays')}</dt><dd>{days(p.business_retention_days)}</dd><dt>{t('deletionCoolingDays')}</dt><dd>{days(p.deletion_cooling_days)}</dd></dl>;
}
export function ApprovalsView({me}:{me:Me}){
 const t=useText(),lang=useLanguage(),step=useStepUp(),w=useWork(),[rows,setRows]=useState<Change[]|null>(null);
 const load=async()=>setRows(await call<Change[]>('GET','/platform/changes'));useEffect(()=>{void load().catch(e=>w.setError(errorText(e)));},[]);
 async function decide(row:Change,approve:boolean){const note=prompt(t('decisionNote'));if(!note?.trim())return;await w.run(async()=>{await step(()=>call('POST',`/platform/changes/${row.id}/decision`,{approve,note}));await load();});}
 return <><h1>{t('navApprovals')}</h1><p className="muted">{t('approvalHint')}</p><Feedback {...w}/><button disabled={w.busy} onClick={()=>w.run(load)}>{t('reloadSettings')}</button>{rows?.map(r=><section className="panel" key={r.id}><h2>{t(r.kind==='recovery'?'staffRecovery':r.kind==='roles'?'approvalRoles':r.kind==='plan'?'approvalPlan':'approvalPolicy')} · {t(r.status==='pending'?'pendingChange':r.status==='approved'?'approvedChange':r.status==='rejected'?'rejectedChange':'obsoleteChange')}</h2><p>{r.requester} · {dateTime(r.created_at,lang)}</p><p>{t('reason')}: {r.reason}</p><ChangeDetails row={r}/>{r.decision_note?<p>{r.decision_note}</p>:null}{r.status==='pending'&&(isSuperAdmin(me)||r.requested_by!==me.id&&r.target_id!==me.id)&&me.permissions.includes(['roles','recovery'].includes(r.kind)?'accounts.approve':r.kind==='plan'?'plans.publish':'policy.approve')?<div className="actions"><button className="primary" disabled={w.busy} onClick={()=>decide(r,true)}>{t('approve')}</button><button className="danger" disabled={w.busy} onClick={()=>decide(r,false)}>{t('reject')}</button></div>:null}</section>)}{rows&&!rows.length?<p>{t('empty')}</p>:null}</>;
}
type DraftPayload={code:string;name_th:string;name_en:string;kind:string;technician_seats:number;storage_bytes:number;ocr_per_period:number;trial_days:number;grace_days:number;effective_at:string;prices:{interval_unit:string;amount_minor:number}[]};
type Draft={id:string;version:number;payload:DraftPayload;status:string};
type PlanVersion=Omit<DraftPayload,'prices'> & {version_no:number;published_at:string;prices:DraftPayload['prices']|null};
type Plan={id:string;version:number;code:string;name_th:string;name_en:string;kind:string;status:string;versions:PlanVersion[]};
export function CatalogView({me}:{me:Me}){
 const t=useText(),lang=useLanguage(),step=useStepUp(),w=useWork(),[data,setData]=useState<{plans:Plan[];drafts:Draft[]}|null>(null),[editing,setEditing]=useState<Draft|null>(null),[open,setOpen]=useState(false);
 const [p,setP]=useState<DraftPayload>({code:'',name_th:'',name_en:'',kind:'paid',technician_seats:1,storage_bytes:1000000000,ocr_per_period:0,trial_days:0,grace_days:0,effective_at:new Date().toISOString(),prices:[]}),[monthly,setMonthly]=useState(''),[yearly,setYearly]=useState(''),[at,setAt]=useState(localTime());
 const load=async()=>setData(await call('GET','/platform/catalog'));useEffect(()=>{void load().catch(e=>w.setError(errorText(e)));},[]);
 function edit(payload:DraftPayload,draft:Draft|null=null){setP(payload);setEditing(draft);setMonthly(String((payload.prices.find(x=>x.interval_unit==='month')?.amount_minor??0)/100||''));setYearly(String((payload.prices.find(x=>x.interval_unit==='year')?.amount_minor??0)/100||''));setAt(localTime(payload.effective_at));setOpen(true);}
 async function save(e:FormEvent){e.preventDefault();await w.run(async()=>{await call('POST','/platform/catalog/drafts',{id:editing?.id,version:editing?.version,payload:{...p,effective_at:instant(at),prices:p.kind==='trial'?[]:[...(monthly?[{interval_unit:'month',amount_minor:Math.round(Number(monthly)*100)}]:[]),...(yearly?[{interval_unit:'year',amount_minor:Math.round(Number(yearly)*100)}]:[])]}});setOpen(false);await load();});}
 async function submit(d:Draft){const reason=prompt(t('confirmationReason'));if(!reason?.trim())return;await w.run(async()=>{await step(()=>call('POST','/platform/changes',{kind:'plan',target_id:d.id,version:d.version,reason}));await load();});}
 async function archive(plan:Plan){const reason=prompt(t('confirmationReason'));if(!reason?.trim())return;await w.run(async()=>{await step(()=>call('POST',`/platform/catalog/${plan.id}/archive`,{version:plan.version,reason}));await load();});}
 return <><h1>{t('navCatalog')}</h1><p className="muted">{t('catalogHint')}</p><Feedback {...w}/><div className="actions"><button className="primary" disabled={w.busy} onClick={()=>edit({...p,code:'',name_th:'',name_en:'',effective_at:new Date().toISOString()})}>{t('newDraft')}</button><button disabled={w.busy} onClick={()=>w.run(load)}>{t('reloadSettings')}</button></div>
 {open?<Editor title={t(editing?'editDraft':'newDraft')} onClose={()=>setOpen(false)}><form onSubmit={save}><div className="grid2">{(['code','name_th','name_en'] as const).map((key,i)=><label key={key}>{t((['planCode','nameTh','nameEn'] as const)[i]!)}<input required maxLength={key==='code'?50:150} pattern={key==='code'?'[a-z][a-z0-9_-]{1,49}':undefined} value={p[key]} onChange={e=>setP({...p,[key]:e.target.value})}/></label>)}<label>{t('planKind')}<select value={p.kind} onChange={e=>setP({...p,kind:e.target.value})}><option value="paid">{t('paidPlan')}</option><option value="trial">{t('trialPlan')}</option></select></label>
 {(['technician_seats','storage_bytes','trial_days','grace_days'] as const).map((key,i)=><label key={key}>{t((['seats','storageGb','trialDays','graceDays'] as const)[i]!)}<input type="number" required min={i===1?1:0} max={i>1?365:undefined} value={key==='storage_bytes'?p[key]/1e9:p[key]} onChange={e=>setP({...p,[key]:Number(e.target.value)*(key==='storage_bytes'?1e9:1)})}/></label>)}
 {p.kind==='paid'?<><label>{t('monthlyPrice')}<input type="number" min="0.01" step="0.01" value={monthly} onChange={e=>setMonthly(e.target.value)}/></label><label>{t('yearlyPrice')}<input type="number" min="0.01" step="0.01" value={yearly} onChange={e=>setYearly(e.target.value)}/></label></>:null}<label>{t('effectiveAt')}<input type="datetime-local" required value={at} onChange={e=>setAt(e.target.value)}/></label></div><button className="primary" disabled={w.busy||p.kind==='paid'&&!monthly&&!yearly}>{t('save')}</button></form></Editor>:null}
 <h2>{t('draftStatus')}</h2>{data?.drafts.map(d=><section className="panel" key={d.id}><h3>{lang==='th'?d.payload.name_th:d.payload.name_en} · {d.payload.code}</h3><p>{t(d.status==='pending'?'pendingChange':'draftStatus')} · {t('versionLabel')} {d.version}</p><div className="actions"><button disabled={w.busy||d.status!=='draft'} onClick={()=>edit(d.payload,d)}>{t('editDraft')}</button><button className="primary" disabled={w.busy||d.status!=='draft'} onClick={()=>submit(d)}>{t(isSuperAdmin(me)?'publishNow':'requestApproval')}</button></div></section>)}{data&&!data.drafts.length?<p className="muted">{t('empty')}</p>:null}
 <h2>{t('navCatalog')}</h2>{data?.plans.map(plan=><section className="panel" key={plan.id}><h3>{lang==='th'?plan.name_th:plan.name_en} · {plan.code}</h3><p>{t(plan.status==='active'?'planActive':'planArchived')}</p><div className="actions"><button disabled={w.busy||!plan.versions.length} onClick={()=>{const v=plan.versions[0];if(!v)return;edit({code:plan.code,name_th:plan.name_th,name_en:plan.name_en,kind:plan.kind,technician_seats:v.technician_seats,storage_bytes:Number(v.storage_bytes),ocr_per_period:v.ocr_per_period,trial_days:v.trial_days,grace_days:v.grace_days,effective_at:new Date().toISOString(),prices:v.prices??[]});}}>{t('copyPlan')}</button>{me.permissions.includes('plans.publish')&&plan.status==='active'?<button className="danger" disabled={w.busy} onClick={()=>archive(plan)}>{t('archivePlan')}</button>:null}</div>{plan.versions.map(v=><details key={v.version_no}><summary>{t('versionLabel')} {v.version_no} · {dateTime(v.published_at,lang)} · {v.prices?.map(pr=>`${money(pr.amount_minor,lang)}/${t(pr.interval_unit==='year'?'priceYear':'priceMonth')}`).join(' · ')||t('trialPlan')}</summary><p>{t('seats')}: {v.technician_seats} · {Number(v.storage_bytes)/1e9} GB · {t('trialDays')} {v.trial_days} · {t('graceDays')} {v.grace_days}</p></details>)}</section>)}</>;
}
export function PolicyView({me}:{me:Me}){const t=useText(),step=useStepUp(),w=useWork(),[data,setData]=useState<{version:number;payload:{new_shops_enabled:boolean;new_payments_enabled:boolean;business_retention_days?:number|null;deletion_cooling_days?:number|null}}|null>(null),[why,setWhy]=useState('');
 const load=async()=>setData(await call('GET','/platform/policy'));useEffect(()=>{void load().catch(e=>w.setError(errorText(e)));},[]);
 return <><h1>{t('navPolicy')}</h1><p>{t('policyHint')}</p><Feedback {...w}/>{data?<form className="panel" onSubmit={e=>{e.preventDefault();void w.run(async()=>{await step(()=>call('POST','/platform/changes',{kind:'policy',version:data.version,payload:data.payload,reason:why}));setWhy('');await load();});}}><p>{t('versionLabel')} {data.version}</p>{(['new_shops_enabled','new_payments_enabled'] as const).map((key,i)=><label className="check" key={key}><input type="checkbox" checked={data.payload[key]} onChange={e=>setData({...data,payload:{...data.payload,[key]:e.target.checked}})}/>{t(i?'allowNewPayments':'allowNewShops')}</label>)}<div className="grid2">{(['business_retention_days','deletion_cooling_days'] as const).map((key,n)=><label key={key}>{t(n?'deletionCoolingDays':'businessRetentionDays')}<input type="number" min={1} max={36500} value={data.payload[key]??''} onChange={e=>setData({...data,payload:{...data.payload,[key]:e.target.value?Number(e.target.value):null}})}/></label>)}</div><p className="muted">{t('privacyPolicyHint')}</p><label>{t('reason')}<textarea required maxLength={500} value={why} onChange={e=>setWhy(e.target.value)}/></label><button className="primary" disabled={w.busy}>{t(isSuperAdmin(me)?'applyNow':'requestApproval')}</button></form>:null}</>;
}
export function Enrollment({token,onDone}:{token:string;onDone:()=>void}){const t=useText(),w=useWork(),[setup,setSetup]=useState<{email:string;display_name:string;secret:string}|null>(null),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[code,setCode]=useState('');
 useEffect(()=>{call<typeof setup>('POST','/platform/enrollment/setup',{token},false).then(setSetup,()=>w.setError(t('inviteInvalid')));},[token]);
 return <form className="signin" onSubmit={e=>{e.preventDefault();if(password!==confirm){w.setError(t('passwordMismatch'));return;}void w.run(async()=>{await call('POST','/platform/enrollment',{token,password,code},false);setSetup(null);setPassword('');setConfirm('');alert(t('enrolled'));onDone();});}}><h1>{t('enrollStaff')}</h1><Feedback {...w}/>{setup?<><p>{setup.display_name} · {setup.email}</p><p>{t('enrollHint')}</p><label>{t('totpSecret')}<input readOnly value={setup.secret} autoComplete="off"/></label><label>{t('newPassword')}<input type="password" autoComplete="new-password" required minLength={12} maxLength={200} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>{t('confirmPassword')}<input type="password" autoComplete="new-password" required minLength={12} maxLength={200} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><label>{t('code')}<input required inputMode="numeric" pattern="\d{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button className="primary" disabled={w.busy}>{t('confirm')}</button></>:null}<button type="button" onClick={onDone}>{t('signIn')}</button></form>;
}
