'use client';
import { useEffect, useState, type FormEvent } from 'react';
import type { AdminKey } from '@field-service/i18n';
import { call, dateTime, useAsk, useLanguage, useStepUp, useText, type Me } from './api';
import { Editor, Feedback, instant, localTime, useWork } from './management';
import { ShopMultiPicker } from './shop-picker';
type Announcement={id?:string;version?:number;title_th:string;title_en:string;body_th:string;body_en:string;audience:string;organization_ids:string[];status:string;publish_at:string;expires_at:string};
type Incident={id?:string;version?:number;title:string;severity:string;status:string;services:string[];timeline?:{at:string;status:string;note:string}[];updated_at?:string};
const audienceKeys:Record<string,AdminKey>={all:'audienceAll',trial:'audienceTrial',paid:'audiencePaid',shops:'audienceShops'};
const severityKeys:Record<string,AdminKey>={low:'severityLow',medium:'severityMedium',high:'severityHigh',critical:'severityCritical'};
const statuses:Record<string,AdminKey>={draft:'draftStatus',scheduled:'scheduled',published:'published',cancelled:'cancelled',investigating:'investigating',identified:'identified',monitoring:'monitoring',resolved:'resolved'};
const services=['api','database','storage','ocr','sms','payment','push','web'];
export function CommunicationsView(){
 const t=useText(),lang=useLanguage(),step=useStepUp(),ask=useAsk(),w=useWork(),[data,setData]=useState<{announcements:Announcement[];incidents:Incident[]}|null>(null),[tab,setTab]=useState<'announcements'|'incidents'>('announcements');
 const [a,setA]=useState<Announcement|null>(null),[i,setI]=useState<Incident|null>(null),[targets,setTargets]=useState<string[]>([]),[at,setAt]=useState(localTime()),[until,setUntil]=useState(localTime(new Date(Date.now()+7*86400000).toISOString())),[note,setNote]=useState('');
 const load=async()=>setData(await call('GET','/platform/communications'));useEffect(()=>{void load().catch(e=>w.setError(e instanceof Error?e.message:String(e)));},[]);
 function editAnnouncement(row?:Announcement){const next=row??{title_th:'',title_en:'',body_th:'',body_en:'',audience:'all',organization_ids:[],status:'draft',publish_at:new Date().toISOString(),expires_at:new Date(Date.now()+7*86400000).toISOString()};setA(next);setTargets(next.organization_ids);setAt(localTime(next.publish_at));setUntil(localTime(next.expires_at));setI(null);}
 function editIncident(row?:Incident){setI(row??{title:'',severity:'medium',status:'investigating',services:['api']});setNote('');setA(null);}
 async function saveAnnouncement(e:FormEvent){e.preventDefault();if(!a)return;await w.run(async()=>{await step(()=>call('POST','/platform/announcements',{...a,publish_at:instant(at),expires_at:instant(until),organization_ids:a.audience==='shops'?targets:[]}));setA(null);await load();});}
 async function withdraw(row:Announcement){if(await ask({title:t('withdraw'),message:lang==='th'?row.title_th:row.title_en,danger:true})===null)return;await w.run(async()=>{await step(()=>call('POST','/platform/announcements',{...row,status:'cancelled'}));await load();});}
 async function saveIncident(e:FormEvent){e.preventDefault();if(!i)return;await w.run(async()=>{await call('POST','/platform/incidents',{...i,note});setI(null);await load();});}
 return <><h1>{t('navCommunications')}</h1><Feedback {...w}/><div className="actions"><button className={tab==='announcements'?'primary':'ghost'} onClick={()=>{setTab('announcements');setI(null);}}>{t('announcementsTitle')}</button><button className={tab==='incidents'?'primary':'ghost'} onClick={()=>{setTab('incidents');setA(null);}}>{t('incidentsTitle')}</button><button disabled={w.busy} onClick={()=>w.run(load)}>{t('reloadSettings')}</button><button disabled={w.busy} onClick={()=>tab==='announcements'?editAnnouncement():editIncident()}>{t(tab==='announcements'?'newAnnouncement':'newIncident')}</button></div>
 {a?<Editor title={t('announcementsTitle')} onClose={()=>setA(null)}><form onSubmit={saveAnnouncement}><div className="grid2">{(['title_th','title_en','body_th','body_en'] as const).map((k,n)=><label key={k}>{t((['titleTh','titleEn','bodyTh','bodyEn'] as const)[n]!)}{k.startsWith('body')?<textarea required maxLength={4000} rows={5} value={a[k]} onChange={e=>setA({...a,[k]:e.target.value})}/>:<input required maxLength={150} value={a[k]} onChange={e=>setA({...a,[k]:e.target.value})}/>}</label>)}<label>{t('audience')}<select value={a.audience} onChange={e=>setA({...a,audience:e.target.value})}>{Object.entries(audienceKeys).map(([value,key])=><option key={value} value={value}>{t(key)}</option>)}</select></label><label>{t('status')}<select value={a.status} onChange={e=>setA({...a,status:e.target.value})}>{['draft','scheduled','published'].map(value=><option key={value} value={value}>{t(statuses[value] ?? 'status')}</option>)}</select></label>{a.audience==='shops'?<div className="span2"><ShopMultiPicker label={t('targetShops')} value={targets} onChange={setTargets}/>{!targets.length?<p className="muted">{t('shopsRequired')}</p>:null}</div>:null}<label>{t('publishAt')}<input type="datetime-local" required value={at} onChange={e=>setAt(e.target.value)}/></label><label>{t('expiresAt')}<input type="datetime-local" required value={until} onChange={e=>setUntil(e.target.value)}/></label></div><button className="primary" disabled={w.busy||a.audience==='shops'&&!targets.length}>{t('save')}</button></form></Editor>:null}
 {i?<Editor title={t('incidentsTitle')} onClose={()=>setI(null)}><form onSubmit={saveIncident}><label>{t('incidentTitle')}<input required maxLength={150} value={i.title} onChange={e=>setI({...i,title:e.target.value})}/></label><div className="grid2"><label>{t('severity')}<select value={i.severity} onChange={e=>setI({...i,severity:e.target.value})}>{Object.entries(severityKeys).map(([value,key])=><option key={value} value={value}>{t(key)}</option>)}</select></label><label>{t('status')}<select value={i.status} onChange={e=>setI({...i,status:e.target.value})}>{['investigating','identified','monitoring','resolved'].map(value=><option key={value} value={value}>{t(statuses[value] ?? 'status')}</option>)}</select></label></div><fieldset><legend>{t('affectedServices')}</legend><div className="actions">{services.map(s=><label className="check" key={s}><input type="checkbox" checked={i.services.includes(s)} onChange={e=>setI({...i,services:e.target.checked?[...i.services,s]:i.services.filter(x=>x!==s)})}/>{s.toUpperCase()}</label>)}</div></fieldset><label>{t('incidentNote')}<textarea required maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary" disabled={w.busy||!i.services.length}>{t('save')}</button></form></Editor>:null}
 {tab==='announcements'?data?.announcements.map(row=><section className="panel" key={row.id}><h2>{lang==='th'?row.title_th:row.title_en}</h2><p className="text-lines">{lang==='th'?row.body_th:row.body_en}</p><p className="muted">{t(statuses[row.status] ?? 'status')} · {t(audienceKeys[row.audience] ?? 'status')} · {dateTime(row.publish_at,lang)} – {dateTime(row.expires_at,lang)}</p><div className="actions">{['draft','scheduled'].includes(row.status)?<button disabled={w.busy} onClick={()=>editAnnouncement(row)}>{t('edit')}</button>:null}{row.status!=='cancelled'?<button className="danger" disabled={w.busy} onClick={()=>withdraw(row)}>{t('withdraw')}</button>:null}</div></section>):data?.incidents.map(row=><section className="panel" key={row.id}><h2>{row.title}</h2><p>{t(statuses[row.status] ?? 'status')} · {t(severityKeys[row.severity] ?? 'status')} · {row.services.join(', ')}</p><button disabled={w.busy} onClick={()=>editIncident(row)}>{t('incidentNote')}</button><details><summary>{t('timeline')}</summary>{row.timeline?.map((entry,n)=><p key={n}>{dateTime(entry.at,lang)} · {t(statuses[entry.status] ?? 'status')}<br/>{entry.note}</p>)}</details></section>)}{data&&!(tab==='announcements'?data.announcements:data.incidents).length?<p>{t('empty')}</p>:null}</>;
}
type QueueRow={id:string;version?:number;organization_id?:string;status?:string;event_type?:string;attempts?:number;created_at:string};
type Check={id:string;kind:string;result:string;evidence:string;checked_at:string;recorded_by_name:string};
export function OperationsView({me}:{me:Me}){
 const t=useText(),lang=useLanguage(),step=useStepUp(),ask=useAsk(),w=useWork(),[data,setData]=useState<{checks:Check[];deliveries:QueueRow[];ocr:QueueRow[];outbox:QueueRow[];webhooks:QueueRow[]}|null>(null);
 const [kind,setKind]=useState('backup'),[result,setResult]=useState('passed'),[evidence,setEvidence]=useState(''),[at,setAt]=useState(localTime());
 const load=async()=>setData(await call('GET','/platform/operations'));useEffect(()=>{void load().catch(e=>w.setError(e instanceof Error?e.message:String(e)));},[]);
 async function record(e:FormEvent){e.preventDefault();await w.run(async()=>{await call('POST','/platform/operations/checks',{kind,result,evidence,checked_at:instant(at)});setEvidence('');await load();});}
 async function retry(row:QueueRow,kind:'deliveries'|'ocr'='deliveries'){const reason=await ask({title:t('confirmTitle'),input:{label:t('confirmationReason'),required:true}});if(!reason?.trim())return;await w.run(async()=>{await step(()=>call('POST',`/platform/operations/${kind}/${row.id}/retry`,{version:row.version,reason}));await load();});}
 async function refresh(row:QueueRow){const reason=await ask({title:t('confirmTitle'),input:{label:t('confirmationReason'),required:true}});if(!reason?.trim())return;await w.run(async()=>{await step(()=>call('POST',`/platform/operations/checkouts/${row.id}/refresh`,{reason}));await load();});}
 return <><h1>{t('navOperations')}</h1><p className="muted">{t('operationsHint')}</p><Feedback {...w}/><button disabled={w.busy} onClick={()=>w.run(load)}>{t('reloadSettings')}</button>{me.permissions.includes('operations.manage')?<form className="panel" onSubmit={record}><h2>{t('recordCheck')}</h2><div className="grid2"><label>{t('checkKind')}<select value={kind} onChange={e=>setKind(e.target.value)}>{['backup','restore','api','storage','ocr','webhook'].map(k=><option key={k} value={k}>{k.toUpperCase()}</option>)}</select></label><label>{t('status')}<select value={result} onChange={e=>setResult(e.target.value)}><option value="passed">{t('passed')}</option><option value="failed">{t('checkFailed')}</option></select></label><label>{t('checkedAt')}<input type="datetime-local" required value={at} onChange={e=>setAt(e.target.value)}/></label><label>{t('checkEvidence')}<textarea required maxLength={1000} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label></div><button className="primary" disabled={w.busy}>{t('recordCheck')}</button></form>:null}
 <h2>{t('recordCheck')}</h2>{data?.checks.map(c=><section className="panel" key={c.id}><strong>{c.kind.toUpperCase()} · {t(c.result==='passed'?'passed':'checkFailed')}</strong><p>{c.evidence}</p><small>{dateTime(c.checked_at,lang)} · {c.recorded_by_name}</small></section>)}
 {(['deliveries','ocr','outbox','webhooks'] as const).map((key,n)=><section className="panel" key={key}><h2>{[ 'Push', 'OCR',t('outboxTitle'),t('webhooksTitle')][n]}</h2><div className="table-scroll"><table><thead><tr><th>ID</th><th>{t('status')}</th><th>{t('attempts')}</th><th>{t('created')}</th><th/></tr></thead><tbody>{data?.[key].map(row=><tr key={row.id}><td><code>{row.id}</code><div className="muted">{row.organization_id}</div></td><td>{row.status??row.event_type}</td><td>{row.attempts??'—'}</td><td>{dateTime(row.created_at,lang)}</td><td>{key==='webhooks'&&me.permissions.includes('operations.manage')?<button disabled={w.busy} onClick={()=>refresh(row)}>{t('refreshCheckout')}</button>:null}{['deliveries','ocr'].includes(key)&&row.status==='failed'&&me.permissions.includes('operations.manage')?<button disabled={w.busy} onClick={()=>retry(row,key==='ocr'?'ocr':'deliveries')}>{t(key==='ocr'?'retryOcr':'retryDelivery')}</button>:null}</td></tr>)}</tbody></table></div>{data&&!data[key].length?<p>{t('empty')}</p>:null}</section>)}</>;
}
