'use client';
import { useEffect, useState } from 'react';
import { call, dateTime, download, isSuperAdmin, useLanguage, useStepUp, useText, type Me } from './api';
import { Editor, Feedback, useWork } from './management';
import { Pager, type Page } from './admin';
type Row={id:string;organization_name:string;request_type:string;status:string;requested_by:string;reason:string|null;created_at:string};
type Preview={request:{id:string;version:number;organization_id:string;request_type:string;status:string;decided_by:string|null;execution_note:string|null};organization_status:string;owner_verified:boolean;policy_configured:boolean;eligible_at:string;holds:{id:string;reason:string;created_at:string}[];counts:Record<string,number>;artifact:{expires_at:string;byte_count:number}|null;erasure_remaining:number;unsettled_payments:number};
export function PrivacyView({me}:{me:Me}){
 const t=useText(),lang=useLanguage(),step=useStepUp(),w=useWork(),[rows,setRows]=useState<Row[]|null>(null),[d,setD]=useState<Preview|null>(null),[note,setNote]=useState(''),[offset,setOffset]=useState(0),[hasMore,setHasMore]=useState(false);
 const load=async()=>{const r=await call<Page<Row>>('GET',`/platform/data-requests?offset=${offset}`);setRows(r.items);setHasMore(r.has_more);};useEffect(()=>{void load().catch(e=>w.setError(e instanceof Error?e.message:String(e)));},[offset]);
 const preview=async(id:string)=>{setD(await call('GET',`/platform/privacy/requests/${id}`));setNote('');};
 async function decision(status:string){if(!d||!note.trim())return;await w.run(async()=>{await step(()=>call('POST',`/platform/data-requests/${d.request.id}`,{status,note}));await preview(d.request.id);await load();});}
 async function execute(exportFile:boolean){if(!d||!note.trim())return;if(!exportFile&&!confirm(t('privacyExecutionHint')))return;await w.run(async()=>{setD(await step(()=>call<Preview>('POST',`/platform/privacy/requests/${d.request.id}/${exportFile?'export':'execute'}`,{version:d.request.version,note})));setNote('');await load();});}
 async function hold(release?:string){if(!d)return;const reason=prompt(t('confirmationReason'));if(!reason?.trim())return;await w.run(async()=>{await step(()=>call('POST','/platform/privacy/holds',{organization_id:d.request.organization_id,release_id:release,reason}));await preview(d.request.id);});}
 async function ledger(){await w.run(async()=>{const result=await step(()=>download('/platform/privacy/tombstones'));const a=document.createElement('a');a.href=result.url;a.download='erasure-ledger.json';a.click();setTimeout(()=>URL.revokeObjectURL(result.url),1000);});}
 const blocked=d&&(!d.owner_verified||d.holds.length>0||d.unsettled_payments>0||(d.request.decided_by===me.id&&!isSuperAdmin(me))||d.request.request_type==='deletion'&&(!d.policy_configured||Date.parse(d.eligible_at)>Date.now()));
 return <><h1>{t('navData')}</h1><p className="muted">{t('privacyExecutionHint')}</p><Feedback {...w}/><div className="actions"><button disabled={w.busy} onClick={()=>w.run(load)}>{t('reloadSettings')}</button>{me.permissions.includes('operations.manage')?<button disabled={w.busy} onClick={ledger}>{t('downloadTombstones')}</button>:null}</div>
 {d?<Editor title={t('privacyPreview')} onClose={()=>setD(null)}><p>{t('type')}: {t(d.request.request_type==='export'?'dataType.export':d.request.request_type==='closure'?'dataType.closure':'dataType.deletion')} · {d.request.status}</p><p>{t('ownerVerified')}: {d.owner_verified?'✓':'—'} · {d.organization_status}</p><p>{t('eligibleAt')}: {dateTime(d.eligible_at,lang)}</p>{d.request.request_type==='deletion'&&!d.policy_configured?<p className="error">{t('privacyPolicyMissing')}</p>:null}<div className="tiles">{Object.entries(d.counts).map(([key,value])=><div className="tile" key={key}><strong>{value}</strong><span>{key}</span></div>)}</div><p>{t('navPayments')}: {d.unsettled_payments}</p><p>{t('erasureRemaining')}: {d.erasure_remaining}</p>
 <h3>{t('legalHolds')}</h3>{d.holds.map(h=><p key={h.id}>{h.reason} · {dateTime(h.created_at,lang)} <button className="danger" disabled={w.busy} onClick={()=>hold(h.id)}>{t('releaseHold')}</button></p>)}<button disabled={w.busy} onClick={()=>hold()}>{t('placeHold')}</button><p className="muted">{t('exportOwnerOnly')}</p>{d.artifact?<p>{t('exportExpires')}: {dateTime(d.artifact.expires_at,lang)} · {d.artifact.byte_count} bytes</p>:null}
 {['pending','approved'].includes(d.request.status)?<><label>{t('note')}<textarea maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="actions">{d.request.status==='pending'?<><button className="primary" disabled={w.busy||!note.trim()||!d.owner_verified} onClick={()=>decision('approved')}>{t('approve')}</button><button className="danger" disabled={w.busy||!note.trim()} onClick={()=>decision('rejected')}>{t('reject')}</button></>:<><button className="primary" disabled={w.busy||!note.trim()||Boolean(d.request.request_type!=='export'&&blocked)} onClick={()=>execute(d.request.request_type==='export')}>{t(d.request.request_type==='export'?'generateExport':'executePrivacy')}</button><button className="danger" disabled={w.busy||!note.trim()} onClick={()=>decision('cancelled')}>{t('cancel')}</button></>}</div></>:null}{d.request.execution_note?<p>{d.request.execution_note}</p>:null}</Editor>:null}
 <div className="table-scroll"><table><thead><tr><th>{t('shop')}</th><th>{t('type')}</th><th>{t('status')}</th><th>{t('requested')}</th><th/></tr></thead><tbody>{rows?.map(r=><tr key={r.id}><td>{r.organization_name}<div className="muted">{r.reason}</div></td><td>{t(r.request_type==='export'?'dataType.export':r.request_type==='closure'?'dataType.closure':'dataType.deletion')}</td><td>{r.status}</td><td>{r.requested_by}<div className="muted">{dateTime(r.created_at,lang)}</div></td><td><button disabled={w.busy} onClick={()=>w.run(()=>preview(r.id))}>{t('privacyPreview')}</button></td></tr>)}</tbody></table></div>{rows&&!rows.length?<p>{t('empty')}</p>:null}<Pager offset={offset} hasMore={hasMore} busy={w.busy} onChange={setOffset}/></>;
}
