'use client';
import { useContext, useEffect, useRef, useState } from 'react';
import { api, type Autopay, type MaintenanceItem, type ContactResult } from './api';
import type { Go } from './OwnerApp';
import { ActionState, Button, dateTime, Empty, Field, LanguageContext, money, Note, Notice, PageTitle, Panel, ResourceState, Select, statusText, toInstant, useAction, useResource, useText, uuid } from './ui';
export function MaintenanceView({ org, go }: { org: string; go: Go }) {
  const t = useText(), lang = useContext(LanguageContext), a = useAction();
  const r = useResource(() => api.maintenance(org), [org]), team = useResource(() => api.team(org), [org]);
  const [bucket, setBucket] = useState(''), [selected, setSelected] = useState<string[]>([]), [assignee, setAssignee] = useState(''), [start, setStart] = useState(''), [end, setEnd] = useState(''), [description, setDescription] = useState('');
  const key = useRef<string | null>(null), chosen = r.data?.items.filter(i => selected.includes(i.id)) ?? [], location = chosen[0]?.location_id;
  return <><PageTitle>{t('maintenance')}</PageTitle><p className="lead muted">{t('maintenanceHint')}</p><ResourceState resource={r} /><ResourceState resource={team} /><ActionState action={a} />
    {r.data ? <><div className="tiles">{(['overdue', 'within_7', 'within_30'] as const).map((b, i) => <Button key={b} className={`tile ${i === 0 ? 'rose' : i === 1 ? 'amber' : 'teal'}`} onClick={() => setBucket(bucket === b ? '' : b)}><strong>{r.data!.counts[b]}</strong><span>{t(b === 'overdue' ? 'maintenanceOverdue' : b === 'within_7' ? 'maintenanceWithin7' : 'maintenanceWithin30')}</span></Button>)}</div>
    {chosen.length ? <Panel title={`${t('bookJob')} · ${chosen.length}`}><form onSubmit={e => { e.preventDefault(); void a.run(async () => {
      const result = await api.bookMaintenance(org, { request_key: key.current ?? (key.current = uuid()), cycle_ids: selected, assignee_member_id: assignee || null, scheduled_start: toInstant(start), scheduled_end: toInstant(end), description: description.trim() || undefined }); key.current = null; go({ section: 'job', id: result.job_id });
    }); }}><p>{chosen.map(i => i.equipment_name || statusText(lang, 'category', i.category)).join(' · ')}</p><div className="grid2"><Field label={t('ownerWeb.start_bangkok_time')} type="datetime-local" value={start} onChange={e => setStart(e.target.value)} /><Field label={t('ownerWeb.end_bangkok_time')} type="datetime-local" value={end} onChange={e => setEnd(e.target.value)} /></div><Select label={t('assignee')} value={assignee} onChange={e => setAssignee(e.target.value)}><option value="">{t('unassignedOption')}</option>{team.data?.members.filter(m => m.status === 'active').map(m => <option key={m.member_id} value={m.member_id}>{m.display_name}</option>)}</Select><Note label={t('jobDescription')} value={description} onChange={e => setDescription(e.target.value)} /><Button type="submit" kind="primary" busy={a.busy}>{t('bookJob')}</Button></form></Panel> : null}
    {r.data.items.filter(i => !bucket || i.bucket === bucket).map(i => <Panel key={`${i.id}:${i.version}`} title={`${i.customer_name || i.customer_phone} · ${i.location_label}`}><p><Button kind="link" onClick={() => go({ section: 'equipment', id: i.equipment_id })}>{i.equipment_name || [statusText(lang, 'category', i.category), i.brand, i.model].filter(Boolean).join(' ')}</Button> · {i.due_date}</p><p>{i.location_address}</p>{i.customer_phone ? <a href={`tel:${i.customer_phone}`}>{i.customer_phone}</a> : null}<p className="muted">{dateTime(i.last_service_at, lang)}</p>{i.last_contact ? <p>{t('lastContact', { result: statusText(lang, 'contact', i.last_contact.result) })} · {i.last_contact.note}</p> : null}
      {i.booked_job_id ? <Button onClick={() => go({ section: 'job', id: i.booked_job_id! })}>{t('openJob')}</Button> : <label className="check"><input type="checkbox" checked={selected.includes(i.id)} disabled={!!location && location !== i.location_id} onChange={e => { setSelected(e.target.checked ? [...selected, i.id] : selected.filter(id => id !== i.id)); key.current = null; }} />{t('alsoBook')}</label>}
      <MaintenanceActions org={org} item={i} onDone={async () => { setSelected([]); key.current = null; await r.reload(); }} /></Panel>)}{!r.data.items.length ? <Empty /> : null}</> : null}</>;
}
function MaintenanceActions({ org, item: i, onDone }: { org: string; item: MaintenanceItem; onDone: () => Promise<void> }) {
  const t = useText(), lang = useContext(LanguageContext), a = useAction(), [open, setOpen] = useState(false), [result, setResult] = useState<ContactResult>('no_answer'), [note, setNote] = useState(''), [next, setNext] = useState(''), [due, setDue] = useState(i.due_date), [reason, setReason] = useState('');
  return <><Button onClick={() => setOpen(!open)}>{t('logContact')} / {t('postpone')}</Button>{open ? <div className="grid2"><form onSubmit={e => { e.preventDefault(); void a.run(async () => { await api.logContact(org, i.id, { result, note: note.trim() || undefined, next_contact_on: next || null }); await onDone(); }, t('contactSaved')); }}><Select label={t('logContact')} value={result} onChange={e => setResult(e.target.value as ContactResult)}>{['no_answer', 'interested', 'call_later', 'declined', 'booked'].map(c => <option key={c} value={c}>{statusText(lang, 'contact', c)}</option>)}</Select><Note label={t('contactNote')} value={note} maxLength={2000} onChange={e => setNote(e.target.value)} /><Field label={t('nextContactOn')} type="date" value={next} onChange={e => setNext(e.target.value)} /><Button kind="primary" type="submit" busy={a.busy}>{t('save')}</Button></form>
    <form onSubmit={e => { e.preventDefault(); void a.run(async () => { await api.postponeCycle(org, i.id, { expected_version: i.version, due_date: due, reason: reason.trim() }); await onDone(); }, t('postponed')); }}><Field label={t('newDueDate')} type="date" required value={due} onChange={e => setDue(e.target.value)} /><Note label={t('reasonLabel')} required maxLength={500} value={reason} onChange={e => setReason(e.target.value)} /><div className="actions"><Button kind="primary" type="submit" busy={a.busy}>{t('postpone')}</Button><Button kind="danger" busy={a.busy} disabled={!reason.trim()} onClick={() => { if (window.confirm(t('stopReminderConfirm'))) void a.run(async () => { await api.stopCycle(org, i.id, reason.trim()); await onDone(); }, t('reminderStopped')); }}>{t('stopReminder')}</Button></div></form></div> : null}<ActionState action={a} /></>;
}
export function BillingView({ org, go }: { org: string; go: Go }) {
  const t = useText(), lang = useContext(LanguageContext), a = useAction(), keys = useRef(new Map<string, string>());
  const r = useResource(async () => { const [subscription, plans, invoices] = await Promise.all([api.subscription(org), api.billingPlans(org), api.invoices(org)]); return { subscription, plans, invoices }; }, [org]);
  return <><PageTitle>{t('subscription')}</PageTitle><ResourceState resource={r} /><ActionState action={a} />{r.data ? <>
    <Panel><h2>{r.data.subscription.plan ? lang === 'th' ? r.data.subscription.plan.name_th : r.data.subscription.plan.name_en : '—'}</h2><p>{statusText(lang, 'sub', r.data.subscription.state)} · {dateTime(r.data.subscription.period_end, lang)}</p>
      {r.data.subscription.usage && r.data.subscription.limits ? <div className="grid2"><p>{t('team')} {r.data.subscription.usage.technician_seats}/{r.data.subscription.limits.technician_seats}</p><p>{t('ownerWeb.photo_storage')} {(r.data.subscription.usage.storage_bytes / 1e9).toFixed(2)}/{(r.data.subscription.limits.storage_bytes / 1e9).toFixed(0)} GB</p></div> : null}
      {r.data.subscription.source === 'paid' ? <Button busy={a.busy} onClick={() => { if (window.confirm(t('ownerWeb.change_your_renewal_preference'))) void a.run(async () => { await api.changeRenewal(org, r.data!.subscription.cancel_at_period_end ? 'resume-renewal' : 'cancel-renewal'); await r.reload(); }); }}>{r.data.subscription.cancel_at_period_end ? t('resumeRenewal') : t('cancelRenewal')}</Button> : null}</Panel>
    <AutopayPanel org={org} />
    <p className="muted">{t('ownerWeb.pilot_plan_prices')}</p>{!r.data.plans.payment_available ? <Notice>{t('ownerWeb.payment_account_is_not_configured_contact_our_team')}</Notice> : null}<div className="plan-grid">{r.data.plans.items.map(p => <Panel key={p.price_version_id} title={lang === 'th' ? p.name_th : p.name_en}><p className="plan-price">{money(p.amount_minor, lang)} <small>{t(p.interval_unit==='year'?'ownerWeb.year':'ownerWeb.month')}</small></p>{p.renewal ? <p className="muted">{t('plan.yourPrice')}</p> : null}{p.change ? <Notice>{t('plan.changeOn', { date: dateTime(p.change.effective_at, lang), price: money(p.change.amount_minor, lang), seats: p.change.technician_seats, storage: Math.round(Number(p.change.storage_bytes) / 1e9) })}</Notice> : null}<p>{p.technician_seats ? `${t('ownerWeb.technicians')} ${p.technician_seats}` : t('ownerOnly')}</p><p>{t('ownerWeb.photo_storage')} {Number(p.storage_bytes) / 1e9} GB</p><p>{t('ocrUnlimited')}</p><Button kind="primary" busy={a.busy} disabled={!r.data!.plans.payment_available} onClick={() => a.run(async () => {
      if (!keys.current.has(p.price_version_id)) keys.current.set(p.price_version_id, uuid());
      const invoice = await api.createInvoice(org, p.price_version_id, keys.current.get(p.price_version_id)!); go({ section: 'invoice', id: invoice.id });
    })}>{t('ownerWeb.choose_plan_create_invoice')}</Button></Panel>)}</div>
    <Panel title={t('ownerWeb.payment_history')}><div className="table-scroll"><table><thead><tr><th>{t('ownerWeb.invoice')}</th><th>{t('ownerWeb.amount')}</th><th>{t('ownerWeb.status')}</th><th>{t('ownerWeb.proof')}</th></tr></thead><tbody>{r.data.invoices.items.map(i => <tr key={i.id}><td><Button kind="link" onClick={() => go({ section: 'invoice', id: i.id })}>{i.number}</Button></td><td>{money(i.amount_minor, lang)}</td><td>{statusText(lang, 'invoice', i.status)}</td><td>{i.proof_status ? statusText(lang, 'proof', i.proof_status) : '—'}</td></tr>)}</tbody></table></div>{!r.data.invoices.items.length ? <Empty /> : null}</Panel></> : null}</>;
}
/** Automatic renewal through Stripe Subscription. Stripe keeps the card; owners change it in Stripe's portal. */
function AutopayPanel({ org }: { org: string }) {
  const t = useText(), lang = useContext(LanguageContext), a = useAction(), r = useResource(() => api.autopay(org), [org]);
  const [state, setState] = useState<Autopay | null>(null), d = state ?? r.data;
  if (!d || (!d.available && !d.subscription)) return null;
  const sub = d.subscription, live = Boolean(sub?.live), date = dateTime(sub?.current_period_end ?? null, lang);
  return <Panel title={t('autopay.title')}><p>{live ? t(sub!.cancel_at_period_end ? 'autopay.onStopping' : 'autopay.on', { date })
    : sub?.canceled_by_owner ? t('autopay.ownerStopped') : sub ? t('autopay.stopped') : t('autopay.off')}</p>
    {live && ['past_due', 'unpaid', 'incomplete'].includes(sub!.status) ? <Notice error>{t('autopay.pastDue')}</Notice> : null}
    <ActionState action={a} />
    <div className="actions">{sub ? <Button busy={a.busy} onClick={() => a.run(async () => { window.location.assign((await api.autopayPortal(org)).url); })}>{t('autopay.manage')}</Button> : null}
    {live ? <Button kind="danger" busy={a.busy} onClick={() => { if (window.confirm(t('autopay.cancelConfirm'))) void a.run(async () => setState(await api.cancelAutopay(org))); }}>{t('autopay.cancel')}</Button> : null}</div></Panel>;
}
export function InvoiceView({ org, id, go }: { org: string; id: string; go: Go }) {
  const t = useText(), lang = useContext(LanguageContext), a = useAction(), r = useResource(() => api.invoice(org, id), [org, id]);
  const [file, setFile] = useState<File | null>(null), proofId = useRef<string | null>(null), i = r.data;
  const checkoutKeys = useRef<Record<string,string>>({}), active = i?.checkouts?.find(c => ['creating','open'].includes(c.status));
  const [subscribe, setSubscribe] = useState(false), autopay = useResource(() => api.autopay(org), [org, i?.status]), autopayLive = Boolean(autopay.data?.subscription?.live);
  useEffect(() => { if (active?.method === 'card') setSubscribe(active.mode === 'subscription'); }, [active?.id]);
  useEffect(() => {
    if (!active || active.status !== 'open') return;
    let checking = false;
    const poll = async () => { if (checking) return; checking = true; try { await api.refreshCheckout(org,id,active.id); await r.reload(); } catch { /* Retry or explicit status check. */ } finally { checking = false; } };
    void poll(); const timer = setInterval(() => void poll(), 10_000); return () => clearInterval(timer);
  }, [org,id,active?.id,active?.status]);
  const startCheckout = (method:'card'|'promptpay') => a.run(async () => {
    if (!active && i?.checkouts?.some(c=>c.method===method&&['expired','failed'].includes(c.status))) { delete checkoutKeys.current[method]; delete checkoutKeys.current['card:subscribe']; }
    // One key per method and choice: a subscription is a different checkout.
    const sub = method === 'card' && subscribe, slot = sub ? 'card:subscribe' : method;
    checkoutKeys.current[slot] ??= uuid();
    try {
      const result = await api.stripeCheckout(org,id,method,checkoutKeys.current[slot],sub);
      await r.reload(); window.location.assign(result.url);
    } catch (error) { await r.reload().catch(() => {}); throw error; }
  });
  return <><Button onClick={() => go({ section: 'billing' })}>← {t('subscription')}</Button><ResourceState resource={r} /><ActionState action={a} />{i ? <><PageTitle action={<Button onClick={() => window.print()}>{t('ownerWeb.print_invoice')}</Button>}>{i.number}</PageTitle><Panel title={lang === 'th' ? i.plan_name_th : i.plan_name_en}><p className="plan-price">{money(i.amount_minor, lang)}</p><p>{statusText(lang, 'invoice', i.status)} · {dateTime(i.created_at, lang)}</p>{i.period ? <p>{dateTime(i.period.start_at, lang)} → {dateTime(i.period.end_at, lang)}</p> : null}
    {i.pay_to ? <dl><dt>{t('ownerWeb.bank')}</dt><dd>{i.pay_to.bank_name}</dd><dt>{t('ownerWeb.account_name')}</dt><dd>{i.pay_to.account_name}</dd><dt>{t('ownerWeb.account_number')}</dt><dd>{i.pay_to.account_number}</dd>{i.pay_to.promptpay_id ? <><dt>PromptPay</dt><dd>{i.pay_to.promptpay_id}</dd></> : null}<dt>{t('ownerWeb.reference')}</dt><dd>{i.pay_to.reference}</dd></dl> : null}</Panel>
    {i.status === 'open' && autopayLive ? <Notice>{t('autopay.blocked')}</Notice> : null}
    {i.status === 'open' && !autopayLive && (i.methods?.stripe_card || i.methods?.stripe_qr || active) ? <Panel title={t('stripe.title')}><p>{t('stripe.hint')}</p>{i.methods?.stripe_test ? <Notice>{t('stripe.test')}</Notice> : null}
      <div className="actions">{i.methods?.stripe_qr ? <Button kind="primary" busy={a.busy} disabled={Boolean(active && active.method !== 'promptpay') || i.proofs.some(p=>p.status==='pending')} onClick={()=>startCheckout('promptpay')}>{t('stripe.qr')}</Button> : null}{i.methods?.stripe_card ? <Button busy={a.busy} disabled={Boolean(active && (active.method !== 'card' || (active.mode === 'subscription') !== subscribe)) || i.proofs.some(p=>p.status==='pending')} onClick={()=>startCheckout('card')}>{t('stripe.card')}</Button> : null}</div>
      {i.methods?.stripe_card ? <label className="check"><input type="checkbox" checked={subscribe} disabled={Boolean(active)} onChange={e => setSubscribe(e.target.checked)} /><span>{t('autopay.subscribe')}<br /><small className="muted">{t('autopay.consent')}</small></span></label> : null}
      {active ? <><p>{statusText(lang,'stripe',active.status)}</p>{active.checkout_url ? <Button onClick={()=>window.location.assign(active.checkout_url!)}>{t('stripe.resume')}</Button> : null}<Button busy={a.busy} onClick={()=>a.run(async()=>{await api.refreshCheckout(org,id,active.id);await r.reload();})}>{t('stripe.refresh')}</Button>{active.status==='open' ? <Button busy={a.busy} onClick={()=>a.run(async()=>{await api.cancelCheckout(org,id,active.id);checkoutKeys.current={};await r.reload();})}>{t('stripe.cancel')}</Button> : null}</> : null}</Panel> : null}
    {i.status === 'open' && i.pay_to && !autopayLive ? <Panel title={t('ownerWeb.upload_transfer_proof')}><Notice>{t('ownerWeb.uploading_a_slip_does_not_renew_the_plan_our')}</Notice><label>{t('choosePhoto')}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={a.busy || Boolean(active)} onChange={e => { setFile(e.target.files?.[0] ?? null); proofId.current = null; }} /></label><Button kind="primary" busy={a.busy} disabled={!file || Boolean(active) || i.proofs.some(p => p.status === 'pending')} onClick={() => a.run(async () => { await api.uploadProof(org, id, proofId.current ?? (proofId.current = uuid()), file!, file!.type); setFile(null); proofId.current = null; await r.reload(); }, t('saved'))}>{t('send')}</Button></Panel> : null}
    {i.checkouts?.filter(c=>c.reason).map(c=><Notice key={c.id}>{statusText(lang,'stripe',c.reason!)}</Notice>)}
    {i.status === 'paid' ? <Notice>{t('paymentActivated')}</Notice> : null}
    <Panel title={t('ownerWeb.proof_review_status')}>{i.proofs.length ? i.proofs.map(p => <p key={p.id}>{statusText(lang, 'proof', p.status)} · {dateTime(p.created_at, lang)} · {p.reason || (p.verification_code ? statusText(lang, 'slip', p.verification_code) : '')}</p>) : <Empty />}</Panel></> : null}</>;
}
export function SupportView({ org }: { org: string }) {
  const t = useText(), lang = useContext(LanguageContext), a = useAction(), r = useResource(() => api.support(org), [org]);
  const [subject, setSubject] = useState(''), [body, setBody] = useState(''), [reply, setReply] = useState<Record<string, string>>({});
  return <><PageTitle>{t('support')}</PageTitle><p className="lead muted">{t('supportHint')}</p><ResourceState resource={r} /><ActionState action={a} />
    <Panel title={t('newTicket')}><form onSubmit={e => { e.preventDefault(); void a.run(async () => { await api.openTicket(org, subject.trim(), body.trim()); setSubject(''); setBody(''); await r.reload(); }, t('saved')); }}><Field label={t('ticketSubject')} required maxLength={200} value={subject} onChange={e => setSubject(e.target.value)} /><Note label={t('ticketBody')} required maxLength={4000} value={body} onChange={e => setBody(e.target.value)} /><Button kind="primary" type="submit" busy={a.busy}>{t('send')}</Button></form></Panel>
    {r.data ? <><Panel title={t('accessRequests')}><p>{t('accessHint')}</p>{r.data.access.filter(g => ['pending', 'active'].includes(g.status)).map(g => <article key={g.id}><h3>{g.agent} · {statusText(lang, 'access', g.status)}</h3><p>{g.reason}</p><p>{g.scope.map(s => statusText(lang, 'scope', s)).join(' · ')} · {t('minutesN', { n: g.duration_minutes })}</p><p>{dateTime(g.valid_until, lang)} · {t('readsN', { n: g.reads })}</p>
      {g.status === 'pending' && !g.consented ? <div className="actions"><Button kind="primary" busy={a.busy} onClick={() => { if (window.confirm(t('ownerWeb.consent_to_this_scope_and_duration_of_access'))) void a.run(async () => { await api.supportAccess(org, g.id, 'consent'); await r.reload(); }); }}>{t('allow')}</Button><Button busy={a.busy} onClick={() => a.run(async () => { await api.supportAccess(org, g.id, 'refuse'); await r.reload(); })}>{t('refuse')}</Button></div> : <><p>{g.status === 'pending' ? t('waitingApproval') : ''}</p><Button kind="danger" busy={a.busy} onClick={() => a.run(async () => { await api.supportAccess(org, g.id, 'revoke'); await r.reload(); })}>{t('revokeAccess')}</Button></>}</article>)}</Panel>
    <Panel title={t('yourTickets')}>{r.data.tickets.length ? r.data.tickets.map(ticket => <details key={ticket.id} className="ticket-details"><summary>{ticket.subject} · {statusText(lang, 'ticket', ticket.status)}</summary><div className="thread">{ticket.messages?.map(m => <div key={m.id} className={`msg ${m.from_platform ? 'team' : 'shop'}`}><small>{m.from_platform ? t('fromTeam') : t('fromYou')} · {dateTime(m.created_at, lang)}</small><p>{m.body}</p></div>)}</div>{ticket.status !== 'closed' ? <form onSubmit={e => { e.preventDefault(); void a.run(async () => { await api.replyTicket(org, ticket.id, (reply[ticket.id] ?? '').trim()); setReply(v => ({ ...v, [ticket.id]: '' })); await r.reload(); }); }}><Note label={t('reply')} required maxLength={4000} value={reply[ticket.id] ?? ''} onChange={e => setReply(v => ({ ...v, [ticket.id]: e.target.value }))} /><Button type="submit" busy={a.busy}>{t('send')}</Button></form> : null}</details>) : <Empty />}</Panel>
    <Panel title={t('requestExport')}>
      {r.data.data_requests.map(d => <p key={d.id}>{dateTime(d.created_at, lang)} · {statusText(lang, 'dataRequest', d.status)} · {d.note}
        {d.type==='export'&&d.status==='succeeded'?<Button busy={a.busy} onClick={()=>a.run(async()=>{
          const body=await api.exportData(org,d.id),url=URL.createObjectURL(new Blob([JSON.stringify(body,null,2)],{type:'application/json'}));
          const link=document.createElement('a');link.href=url;link.download=`shop-export-${d.id}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
        })}>{t('ownerWeb.download_export')}</Button>:null}</p>)}
      <p className="muted">{t('ownerWeb.privacy_request_hint')}</p><div className="actions">
        {(['export','closure','deletion'] as const).map(kind=><Button key={kind} busy={a.busy} disabled={r.data!.data_requests.some(d=>d.type===kind&&['pending','approved','running'].includes(d.status))} onClick={()=>{
          if(window.confirm(t(kind==='export'?'requestExport':kind==='closure'?'ownerWeb.request_closure':'ownerWeb.request_deletion')))void a.run(async()=>{await api.requestExport(org,kind);await r.reload();},t('exportRequested'));
        }}>{t(kind==='export'?'requestExport':kind==='closure'?'ownerWeb.request_closure':'ownerWeb.request_deletion')}</Button>)}
      </div>
    </Panel></> : null}</>;
}
