'use client';
import { useEffect, useRef, useState } from 'react';
const screens = [
 { image: 'app-jobs', name: 'จัดคิวงาน', title: 'รู้ว่าวันนี้มีงานไหน ใครรับผิดชอบ', description: 'เจ้าของร้านดูงานวันนี้ งานถัดไป และงานที่รอมอบหมายจากรายการเดียว เปิดรายละเอียดแล้วเลื่อนนัดหรือเปลี่ยนช่างได้ตามสิทธิ์', points: ['ระบุลูกค้า สถานที่ ประเภทงาน และวันนัด', 'ผูกอุปกรณ์ที่ต้องบริการกับงาน', 'ติดตามสถานะมอบหมายแล้วและกำลังทำงาน'], role: 'เจ้าของร้าน' },
 { image: 'app-technician', name: 'งานของช่าง', title: 'ช่างเปิดแอป แล้วรู้ว่าจะไปทำอะไร', description: 'งานที่ได้รับมอบหมายมาอยู่ในหน้าวันนี้ พร้อมวันเวลา สถานที่ และสถานะ ช่างเข้ารายละเอียดเพื่อดูเครื่องที่จะทำและข้อมูลก่อนเข้าบริการ', points: ['ดูเฉพาะงานและข้อมูลตามสิทธิ์ของตน', 'เปิดข้อมูลสถานที่และปุ่มนำทาง', 'เริ่มงานและบันทึกผลจากงานที่รับผิดชอบ'], role: 'ช่างหน้างาน' },
 { image: 'app-job-detail', name: 'รายละเอียดงาน', title: 'ส่งต่องาน พร้อมข้อมูลที่ช่างต้องรู้', description: 'รายละเอียดบริการ ที่อยู่ หมายเหตุทางเข้า ผู้รับงาน และรายการเครื่อง อยู่ในหน้าของงานเดียว ลดการถามข้อมูลซ้ำระหว่างหน้าร้านกับหน้างาน', points: ['บันทึกข้อความที่ต้องแจ้งช่างก่อนเดินทาง', 'เห็นรุ่นเครื่องและหมายเลขประจำเครื่อง', 'เจ้าของเปลี่ยนผู้รับงานหรือเลื่อนนัดได้'], role: 'เจ้าของร้านและช่าง' },
 { image: 'app-service', name: 'บันทึกผล', title: 'งานเสร็จ พร้อมประวัติที่ใช้ต่อได้', description: 'ช่างบันทึกผลแยกตามเครื่อง เลือกทำแล้ว ไม่ได้ทำ หรือเลื่อน พร้อมเหตุผล แนบรูปก่อน–หลัง และกำหนดรอบดูแลครั้งถัดไปตามงานที่ทำ', points: ['บันทึกบริการและหมายเหตุรายเครื่อง', 'แนบรูปจากกล้องหรือคลังภาพเมื่อออนไลน์', 'ตรวจรายละเอียดก่อนยืนยันส่งผลบริการ'], role: 'ผู้รับผิดชอบงาน' },
 { image: 'app-customer', name: 'ลูกค้าและสถานที่', title: 'ลูกค้าหนึ่งราย หลายสถานที่ ก็จัดการได้', description: 'เปิดข้อมูลลูกค้าแล้วเห็นสถานที่บริการ อุปกรณ์ และข้อมูลทางเข้า สร้างงานจากสถานที่นั้นได้โดยไม่ต้องพิมพ์ข้อมูลเดิมใหม่ทุกครั้ง', points: ['เก็บชื่อ เบอร์โทร และหมายเหตุลูกค้า', 'แยกสาขาหรือสถานที่ของลูกค้าแต่ละราย', 'เลือกบันทึกพิกัดครั้งเดียวเมื่ออยู่หน้างาน'], role: 'เจ้าของร้านและสมาชิกตามสิทธิ์' },
 { image: 'app-equipment', name: 'ข้อมูลเครื่อง', title: 'จำเครื่องได้ แม้เปลี่ยนคนไปบริการ', description: 'เครื่องแต่ละเครื่องมีข้อมูลยี่ห้อ รุ่น Serial และประวัติบริการในที่เดียว เพิ่มรูปป้ายเครื่องแล้วใช้ AI ช่วยอ่านข้อมูล ก่อนตรวจสอบและบันทึก', points: ['เปิดรายละเอียดเครื่องจากสถานที่ของลูกค้า', 'ค้นประวัติบริการเพื่อเตรียมงานครั้งต่อไป', 'ผลอ่านป้ายด้วย AI เป็นข้อเสนอให้ตรวจสอบ'], role: 'เจ้าของร้านและสมาชิกตามสิทธิ์' },
];
export function ProductHero(){return <div className="ps-hero-art"><div className="ps-orbit"/><div className="ps-hero-label">จากหน้าร้าน → ถึงหน้างาน</div><div className="ps-phone ps-hero-back"><img src="/screenshots/app-jobs.png" alt="หน้ารายการงานบริการของแอปคู่ช่าง แสดงวันนัด ผู้รับผิดชอบ และสถานะงานด้วยข้อมูลสาธิต" width="390" height="844" fetchPriority="high"/></div><div className="ps-phone ps-hero-front"><img src="/screenshots/app-technician.png" alt="หน้าวันนี้ของช่างในแอปคู่ช่าง แสดงงานที่ได้รับมอบหมาย" width="390" height="844" fetchPriority="high"/></div><div className="ps-hero-badge"><span>✓</span><div><b>ทีมเห็นงานตรงกัน</b><small>ลูกค้า · เครื่อง · ผลบริการ</small></div></div></div>;}
export function ProductShowcase(){
 const [selected,setSelected]=useState(0); const dialog=useRef<HTMLDialogElement>(null); const current=screens[selected] ?? screens[0]!;
 useEffect(()=>{const d=dialog.current; if(!d)return; const close=(e:MouseEvent)=>{if(e.target===d)d.close();};d.addEventListener('click',close);return()=>d.removeEventListener('click',close);},[]);
 return <>
 <section className="ps-intro" aria-label="ประโยชน์สำหรับเจ้าของและช่าง"><div><span className="lp-kicker">สองบทบาท เชื่อมด้วยข้อมูลชุดเดียว</span><h2>เจ้าของวางแผนได้<br/>ช่างทำงานต่อได้ทันที</h2></div><article><span className="ps-icon">01 / เจ้าของร้าน</span><h3>จัดทีมและเห็นภาพรวม</h3><p>สร้างงาน มอบหมายช่าง ดูสถานะ จัดการลูกค้าและอุปกรณ์ พร้อมติดตามรอบดูแลผ่านเว็บหรือแอป</p></article><article><span className="ps-icon">02 / ช่างหน้างาน</span><h3>พกข้อมูลงานไปกับตัว</h3><p>ดูงานที่รับผิดชอบ เปิดข้อมูลสถานที่ บันทึกบริการและรูปภาพ โดยเจ้าของไม่ต้องถามข้อมูลซ้ำในแชต</p></article></section>
 <section id="screens" className="ps-showcase lp-section"><div className="ps-heading"><span className="lp-kicker">เปิดดู ก่อนเริ่มใช้</span><h2>เห็นหน้าจอ เข้าใจวิธีทำงาน</h2><p className="lp-desc">เลือกขั้นตอนที่อยากดู แล้วสำรวจหน้าจอและสิ่งที่ทำได้จริง</p></div><div className="ps-select" role="group" aria-label="เลือกหน้าจอแอป">{screens.map((s,i)=><button key={s.image} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{s.name}</button>)}</div><div className="ps-stage"><div className="ps-screen-wrap"><span className="ps-screen-tag">{current.role}</span><button className="ps-image-button" onClick={()=>dialog.current?.showModal()} aria-label={`ขยายภาพหน้าจอ ${current.name}`}><img src={`/screenshots/${current.image}.png`} alt={`หน้าจอจริงของแอปคู่ช่าง: ${current.name} ใช้ข้อมูลสาธิต`} width="390" height="844" loading="lazy"/></button><span className="lp-small">แตะภาพเพื่อดูขนาดใหญ่</span></div><div className="ps-explain"><span className="ps-counter">0{selected+1} / 06</span><h3>{current.title}</h3><p>{current.description}</p><ul>{current.points.map(p=><li key={p}>{p}</li>)}</ul><a className="lp-primary" href="/shop?signup=1&lang=th">ทดลองใช้ฟรี 14 วัน ↗</a><p className="ps-disclosure">ภาพจากโค้ดแอปคู่ช่างจริงที่แสดงผ่านเว็บด้วยข้อมูลสาธิต รูปแบบบน Android/iOS อาจต่างเล็กน้อยตามอุปกรณ์</p></div></div><dialog ref={dialog} className="ps-dialog" aria-label={`ภาพหน้าจอ ${current.name}`}><button autoFocus className="ps-dialog-close" onClick={()=>dialog.current?.close()}>ปิดภาพ ×</button><img src={`/screenshots/${current.image}.png`} alt={`ภาพขยายหน้าจอ ${current.name}`} width="390" height="844"/></dialog></section>
 <section className="ps-story"><div className="ps-story-copy"><span className="lp-kicker">ข้อมูลเดิม สร้างโอกาสงานครั้งใหม่</span><h2>บริการจบ<br/>การดูแลยังไปต่อ</h2><p>เมื่อเครื่องถึงกำหนด เจ้าของร้านเปิดรายการรอบดูแลเพื่อติดต่อลูกค้า บันทึกผลการติดต่อ และนัดงานบริการครั้งถัดไปจากข้อมูลเครื่องเดิม</p><div className="ps-timeline"><div><b>บันทึกผลครั้งนี้</b><span>เก็บสิ่งที่ทำและกำหนดรอบถัดไป</span></div><div><b>ติดตามเครื่องถึงรอบ</b><span>ดูรายการเลยกำหนดและใกล้ถึงกำหนด</span></div><div><b>ติดต่อแล้วนัดงาน</b><span>รู้ว่าใครสนใจ ใครขอให้โทรกลับ</span></div></div><p className="lp-small">การติดต่อลูกค้าเป็นการดำเนินการของร้าน ระบบช่วยจัดรายการและบันทึกผล</p></div><div className="ps-connected"><div><span>ลูกค้า</span><b>ร้านกาแฟริมสวน</b><small>ข้อมูลสาธิตเพื่ออธิบายการเชื่อมข้อมูล</small></div><span className="ps-connect-arrow">↓</span><div><span>อุปกรณ์</span><b>แอร์ผนัง · ห้องรับรอง</b><small>รุ่น DA-12000 · Serial DEMO-0001</small></div><span className="ps-connect-arrow">↓</span><div><span>บริการและรอบดูแล</span><b>ประวัติเดียว ใช้ต่อได้ทุกครั้ง</b><small>ผลบริการ → วันครบกำหนด → นัดใหม่</small></div></div></section>
 </>;
}
